import type {
  MonitoringWidgetConfig,
  MonitoringWidgetKind,
  MonitoringWidgetLibraryItem,
} from "@/types/monitoring";

export const DEFAULT_KPI_STRIP = [
  "avg_cssr_ps",
  "avg_ps_rab_sr",
  "avg_iub_congestion",
  "avg_call_drop_dch",
  "avg_throughput",
];

export const WIDGET_LIBRARY: MonitoringWidgetLibraryItem[] = [
  {
    kind: "trend-line",
    label: "Line Trend",
    description: "Time-series line chart for a KPI.",
    defaultTitle: "Primary KPI Trend",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "xl",
    defaultSubtitle: "KPI behavior over selected monitoring scope",
  },
  {
    kind: "trend-area",
    label: "Area Trend",
    description: "Area chart for KPI evolution over time.",
    defaultTitle: "KPI Area Trend",
    defaultMetricKey: "avg_iub_congestion",
    defaultSize: "lg",
    defaultSubtitle: "Area view of KPI evolution",
  },
  {
    kind: "ranking-bar",
    label: "Ranking Bar",
    description: "Ranking view for regions, cells, or entities.",
    defaultTitle: "Regional KPI Ranking",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "md",
    defaultSubtitle: "Top or bottom performing entities",
  },
  {
    kind: "worst-cells-table",
    label: "Worst Cells Table",
    description: "Operational table of the worst-performing cells.",
    defaultTitle: "Top 10 Worst Cells",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "lg",
    defaultSubtitle: "Lowest-performing cells in current scope",
  },
  {
    kind: "distribution",
    label: "Distribution",
    description: "Histogram or bucket distribution for a KPI.",
    defaultTitle: "KPI Distribution",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "md",
    defaultSubtitle: "Distribution of KPI values",
  },
  {
    kind: "radar",
    label: "Radar Chart",
    description: "Multi-KPI shape comparison widget.",
    defaultTitle: "Multi-KPI Health Shape",
    defaultMetricKey: "multi_kpi",
    defaultSize: "md",
    defaultSubtitle: "Radar comparison across KPI families",
  },
  {
    kind: "gauge",
    label: "Gauge Widget",
    description: "Gauge view for aggregate KPI health.",
    defaultTitle: "Network Health Gauge",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "sm",
    defaultSubtitle: "Health band for selected KPI",
  },
  {
    kind: "tube",
    label: "Tube Widget",
    description: "Vertical fill widget for KPI health.",
    defaultTitle: "Network Health Tube",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "sm",
    defaultSubtitle: "Vertical health band",
  },
  {
    kind: "kpi-summary",
    label: "KPI Summary",
    description: "Compact KPI tile with value and threshold.",
    defaultTitle: "KPI Summary",
    defaultMetricKey: "avg_cssr_ps",
    defaultSize: "sm",
    defaultSubtitle: "Current KPI snapshot",
  },
  {
    kind: "scope-summary",
    label: "Scope Summary",
    description: "Compact summary of current monitoring scope.",
    defaultTitle: "Scope Status",
    defaultMetricKey: "scope",
    defaultSize: "sm",
    defaultSubtitle: "Current technology and filter context",
  },
];

export const DEFAULT_WORKSPACE_WIDGETS: Omit<MonitoringWidgetConfig, "id">[] = [
  {
    kind: "trend-line",
    title: "Primary KPI Trend",
    subtitle: "KPI behavior over selected monitoring scope",
    metricKey: "avg_cssr_ps",
    size: "xl",
    visible: true,
    order: 1,
    scopeMode: "global",
  },
  {
    kind: "ranking-bar",
    title: "Regional KPI Ranking",
    subtitle: "Top regional KPI performance",
    metricKey: "avg_cssr_ps",
    size: "md",
    visible: true,
    order: 2,
    scopeMode: "global",
  },
  {
    kind: "worst-cells-table",
    title: "Top 10 Worst Cells",
    subtitle: "Lowest-performing cells in current scope",
    metricKey: "avg_cssr_ps",
    size: "lg",
    visible: true,
    order: 3,
    scopeMode: "global",
  },
  {
    kind: "distribution",
    title: "KPI Distribution",
    subtitle: "Distribution of KPI values",
    metricKey: "avg_cssr_ps",
    size: "md",
    visible: true,
    order: 4,
    scopeMode: "global",
  },
  {
    kind: "radar",
    title: "Multi-KPI Health Shape",
    subtitle: "Radar comparison across KPI families",
    metricKey: "multi_kpi",
    size: "md",
    visible: true,
    order: 5,
    scopeMode: "global",
  },
  {
    kind: "gauge",
    title: "Network Health Gauge",
    subtitle: "Health band for selected KPI",
    metricKey: "avg_cssr_ps",
    size: "sm",
    visible: true,
    order: 6,
    scopeMode: "global",
  },
  {
    kind: "trend-area",
    title: "IUB Congestion Trend",
    subtitle: "Trend view of congestion behavior",
    metricKey: "avg_iub_congestion",
    size: "lg",
    visible: true,
    order: 7,
    scopeMode: "global",
  },
  {
    kind: "trend-area",
    title: "Throughput Trend",
    subtitle: "Trend view of throughput behavior",
    metricKey: "avg_throughput",
    size: "lg",
    visible: true,
    order: 8,
    scopeMode: "global",
  },
];

export function getWidgetLibraryItem(kind: MonitoringWidgetKind) {
  return WIDGET_LIBRARY.find((item) => item.kind === kind) ?? null;
}